project_name: amur
version: 2
force_token: gitea

gitea_urls:
  api: https://vc.maxkaya.com/api/v1
  download: https://vc.maxkaya.com
  skip_tls_verify: true

release:
  gitea:
    owner: maxpeterkaya
    name: amur

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
      - netbsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    binary: amur

archives:
  - id: binary
    formats: ["binary"]
    name_template: "amur_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 \"v1\") }}{{ .Amd64 }}{{ end }}"

  - id: tar
    formats: ["tar.gz"]

dockers_v2:
  - id: web-proxy
    ids:
      - binary
      - amur
    images:
      - "vc.maxkaya.com/maxpeterkaya/amur"
    tags:
      - "v{{ .Version }}"
      - "{{ .Version }}"
      - "latest"
    labels:
      "org.opencontainers.image.description": "{{.ProjectName}}"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
    platforms:
      - linux/amd64
    sbom: "{{ not .IsNightly }}"

source:
  enabled: true

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^test:'
      - '^chore'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy

  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999