name: CI

on:
  push:
    tags:
      - '*'

permissions: read-all

jobs:
  build:
    if: ${{ !contains(github.ref, '-dev') }}

    container:
      image: node:20-alpine
      options: --privileged

    runs-on: arch

    steps:
      - name: Install Docker CLI
        run: apk add --no-cache docker-cli git ca-certificates
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: vc.maxkaya.com
          username: maxpeterkaya
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "^1"
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run GoReleaser
        uses: https://vc.maxkaya.com/workflows/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITEA_TOKEN: ${{ secrets.DOCKER_TOKEN }}